-- source.lua
 -- G-Mon Hub Logic 
local Players = game:GetService("Players") local RepStore = game:GetService("ReplicatedStorage")

-- Utility attack function local function attack(npc) local char=Players.LocalPlayer.Character if char and npc and npc:FindFirstChild("HumanoidRootPart") then char.HumanoidRootPart.CFrame = npc.HumanoidRootPart.CFrame * CFrame.new(0,5,0) firetouchinterest(char.HumanoidRootPart,npc.HumanoidRootPart,0) wait(0.1) firetouchinterest(char.HumanoidRootPart,npc.HumanoidRootPart,1) end end

-- Loops spawn(function() while true do wait() if _G.Flags.ESP then -- simple nametag ESP for _,v in pairs(Players:GetPlayers()) do if v.Character and not v.Character:FindFirstChild("ESP_Tag") then local bill=Instance.new("BillboardGui",v.Character.Head) bill.Name="ESP_Tag";bill.Size=UDim2.new(0,100,0,50);bill.StudsOffset=Vector3.new(0,2,0) local lbl=Instance.new("TextLabel",bill) lbl.Size=UDim2.new(1,0,1,0);lbl.Text=v.Name;lbl.TextColor3=Color3.new(1,0,0) end end end if _G.Flags.Wallbang then -- no-clip local char=Players.LocalPlayer.Character if char then for _,p in pairs(char:GetChildren()) do if p:IsA("BasePart") then p.CanCollide=false end end end end if _G.Flags.AutoFarm then local hrp=Players.LocalPlayer.Character and Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart") if hrp then local nearest,d=nil,math.huge for _,npc in pairs(workspace.Enemies:GetChildren()) do if npc:FindFirstChild("HumanoidRootPart") and npc:FindFirstChild("Humanoid") and npc.Humanoid.Health>0 then local dist=(npc.HumanoidRootPart.Position-hrp.Position).Magnitude if dist<d then d=dist;nearest=npc end end end if nearest then for i=1,3 do attack(nearest);wait(_G.Config.FarmInterval) end end end end if _G.Flags.AutoChest then for _,c in pairs(workspace.Chests:GetChildren()) do if (c.Position-Players.LocalPlayer.Character.HumanoidRootPart.Position).Magnitude<20 then firetouchinterest(Players.LocalPlayer.Character.HumanoidRootPart,c,0) wait(0.1) firetouchinterest(Players.LocalPlayer.Character.HumanoidRootPart,c,1) end end end -- Add loops for other flags similarly... end end)

print("G-Mon Hub logic loaded")

